version: '3'
networks:
  web:
    external: true

services:
  web:
    image: nginx:1.15-alpine
    volumes:
    - ../src/:/usr/share/nginx/html/:ro
    networks:
    - web
    expose:
      - "80"
    labels:
    - "traefik.enable=true"
    - "traefik.docker.network=web"
    - "traefik.protocol=http"
    - "traefik.port=80"
    - "traefik.frontend.rule=Host:wom.social"
    - "traefik.frontend.entryPoints=http,https"
    - "traefik.frontend.redirect.entryPoint=https"
